Feat/148 apple script meetingstart
leits/MeetingBar pull request #166
Opened 2021-01-27 22:25 UTC by jgoldhammer

### Status
**IN DEVELOPMENT**

### Description

The PR is a first attempt to implement the feature request from #148

- first version which will run automatically an apple script within a predefined timeframe before the meeting starts
- we will store the events by id and last modification date, so that the apple script is only run once for an event
- we will collect some event metadata and pass them into the applescript as event parameter
- we expect a file meetingStartScript.scpt in the scripts folder of the application /Users/<user>/Library/Application Scripts/leits.MeetingBar/meetingStartScript.scpt -> if the file is not found, an alert is shown for the user
- user can configure the feature in the advanced tab
 -> user can switch the feature on (by default it is off)
 -> user can configure the timeframe when the script should be executed before the meeting starts
 -> user can test the script execution by pressing the button Test

This is experimental - expect bugs :-)

An example script looks like this:

 ```
# the method to be called with the following parameters for the next meeting.
 #
 # 1. parameter - eventId (string) - unique identifier from apples eventkit implementation
 # 2. parameter - title (string) - the title of the event (event title can be null, although it makes no sense!)
 # 3. parameter - allday (bool) - true for allday events, false for non allday events
 # 4. parameter - startDate (date) - needs casting in apple script to output (e.g. startDate as text)
 # 5 .parameter - endDate (date) - needs casting in apple script to output (e.g. startDate as text)
 # 6. parameter - eventLocation (string) - if no location is set, the value will be "EMPTY"
 # 7. parameter - repeatingEvent (bool) - true if it is part of an repeating event, false for single event
 # 8. parameter - attendeeCount (int32) - number of attendees- 0 for events without attendees
 # 9. parameter - meetingUrl (string) - the url to the meeting found in notes, url or location - only one meeting url is supported - if no meeting url is set, the value will be "EMPTY"
 # 10. parameter - meetingService (string), e.g MS Teams or Zoom- if no meeting service is found, the meeting service value is "EMPTY"
 # 11. parameter - meetingNotes (string)- the complete notes of a meeting -  if no notes are set, value "EMPTY" will be used

on meetingStart(eventId, title, allday, startDate, endDate, eventLocation, repeatingEvent, attendeeCount, meetingUrl, meetingService, meetingNotes)
    tell application "Finder"
        activate
        display dialog title buttons {"OK"} default button "OK"
    end tell
end meetingStart
```

### Steps to Test or Reproduce
- Use the sample script above and use this as template for file `meetingStartScript.scpt` in folder `/Users/<user>/Library/Application Scripts/leits.MeetingBar/`
- Open the preference dialog, navigate to advanced tab and press Test -> a dialog with a sample event title will be shown
- Switch on the automatic execution of the apple script in the preference dialog and schedule a meeting with an online meeting - wait until the apple script get executed.

A small impression of the preference dialog:
![image](https://user-images.githubusercontent.com/3872101/106062173-b9c74e00-60f6-11eb-995e-6108eb1c509d.png)

2021-01-28 16:12 UTC, leits commented
Looks like the toggle "Run meetings when you actively join the meeting" is a suboption for the run script condition.
I don't see a case when the user run one script 3 minutes before and another one when clicking "join"

2021-01-28 19:15 UTC, jgoldhammer commented
There might be cases - automatically run to get a notification (that was the usecase in the ticket), run on click when you want to hide desktop or set dnd to on.

I would not restrict the usage here or do you see any problem?

2021-01-30 18:18 UTC, jgoldhammer commented
How to proceed with this? Merge it and mark it experimental? Or leave it open? @leits ?

2021-02-07 10:15 UTC, leits commented
Sorry for the delay, @jgoldhammer. I was preparing 3.0 to release.
I'll take a deeper look at these changes in the next few days, so let's leave this open for now.

2021-02-19 19:37 UTC, jgoldhammer commented
> Sorry for the delay, @jgoldhammer. I was preparing 3.0 to release.
> I'll take a deeper look at these changes in the next few days, so let's leave this open for now.

What do you think about this? Should we concentrate on the bugs for now and not on new features? We can still leave the pull request open?

2021-04-05 20:30 UTC, jgoldhammer commented
I think this feature would help a lot of people, but the PR is very old.
How to proceed here, @leits?

2021-04-05 20:48 UTC, leits commented
Let's update this and merge.

I think about moving scripts edit form in modal with explicit "Save" for closing.

2021-04-24 13:03 UTC, jgoldhammer commented
> Let's update this and merge.
> 
> I think about moving scripts edit form in modal with explicit "Save" for closing.

Good idea.

2021-04-24 13:06 UTC, jgoldhammer commented
I have updated the PR to the current master and hope to get it included soon. I think, it would work for a first version. We can iterate over it in next versions if there is a demand of the users.

2021-04-25 12:33 UTC, leits requested changes

2021-04-25 12:33 UTC, leits commented on MeetingBar/AppDelegate.swift
> +        Scripts().scheduleRunScriptForMeetingStart()
It's better to first check that the user has enabled this feature.

2021-04-25 12:33 UTC, leits commented on MeetingBar/AppDelegate.swift
> +        let timer = Timer(timeInterval: 15, target: self, selector: #selector(updateStatusbar), userInfo: nil, repeats: true)
Could you make these changes as a separate pull request?

2021-04-25 12:33 UTC, leits commented on MeetingBar/Extensions/Date.swift
> +//  Date.swift
Missing in `MeetingBar.xcodeproj/project.pbxproj`

2021-04-25 12:33 UTC, leits commented on MeetingBar/Scripts.swift
> +                var events = Defaults[.processedEvents]
We need to clean up old meetings from here.
For example, remove events older than a week.

Also, I'm not sure if the ID for recurrent events is different between occurrences.

2021-04-25 12:33 UTC, leits commented on MeetingBar/Extensions/EventStore.swift
> +            if event.isAllDay && Defaults[.allDayEvents] == AlldayEventsAppereance.hide {
Bugfix? :)

2021-04-25 12:33 UTC, leits commented on MeetingBar/Scripts.swift
> +        eventStore = EKEventStore()
Do we need a new instance of the eventstore?

2021-04-25 12:33 UTC, leits commented on MeetingBar/Scripts.swift
> +class Scripts: NSObject {
I see a lot of duplicate logic from other classes from other parts of the application.
I don't think it makes sense to do that. I do not see isolated use of this class only.

2021-04-25 15:32 UTC, jgoldhammer commented on MeetingBar/Views/Preferences/AdvancedTab.swift
> +                    Text("Test")
No, it is a feature :-) Users can test the script with a sample event and check how the own apple script works.

2021-04-25 15:33 UTC, jgoldhammer commented on MeetingBar/AppDelegate.swift
> +        Scripts().scheduleRunScriptForMeetingStart()
But, the user can enable it during runtime, so we need to schedule it again. I have checked in the timer implementation if the feature is enabled. WDYT?

2021-04-25 15:34 UTC, jgoldhammer commented on MeetingBar/AppDelegate.swift
> +        let timer = Timer(timeInterval: 15, target: self, selector: #selector(updateStatusbar), userInfo: nil, repeats: true)
Yes, I could - this was to do so here...

2021-04-25 15:35 UTC, jgoldhammer commented on MeetingBar/Extensions/EventStore.swift
> +            if event.isAllDay && Defaults[.allDayEvents] == AlldayEventsAppereance.hide {
I guess this was merged from master?

2021-04-25 15:36 UTC, jgoldhammer commented on MeetingBar/Scripts.swift
> +        eventStore = EKEventStore()
Not at all maybe- I am not sure if we should reuse the old one because we access it from different threads. What do you think?

2021-04-25 15:38 UTC, jgoldhammer commented on MeetingBar/Scripts.swift
> +class Scripts: NSObject {
Ok - can you be more specific? 
Thx!

2022-03-29 19:21 UTC, jgoldhammer commented on MeetingBar/Extensions/Date.swift
> +//  Date.swift
Now part of the project

2022-04-03 16:22 UTC, jgoldhammer commented on MeetingBar/Scripts.swift
> +                var events = Defaults[.processedEvents]
I have builtin a method to cleanup the events...

2022-04-10 14:55 UTC, jgoldhammer commented
@leits - it is possible to review this again? I think this would be a great feature for some users as we combine an apple script api and the automatic start of events...

2022-04-10 21:27 UTC, leits approved these changes
I left only one comment, and I'm going to merge changes after your responce.

PR - LGTM. Great work, Jens! 
Sorry, it took so long.

When I merge this with calendar providers features, I'll have the possibility to dive deeper.

2022-04-10 21:27 UTC, leits commented on MeetingBar/AppDelegate.swift
> -    func userNotificationCenter(_: UNUserNotificationCenter, willPresent _: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
Why did you delete this function?
`implementation is necessary to show notifications even when the app has focus!`?

2022-04-16 15:25 UTC, jgoldhammer commented on MeetingBar/AppDelegate.swift
> -    func userNotificationCenter(_: UNUserNotificationCenter, willPresent _: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
I will revert it. Was not my intention to delete it...

2022-04-16 15:29 UTC, jgoldhammer commented on MeetingBar/AppDelegate.swift
> -    func userNotificationCenter(_: UNUserNotificationCenter, willPresent _: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
Thanks @leits - looking forward to have it in the master branch and have a release soon!

2022-04-17 21:00 UTC, leits commented
Merged manually in https://github.com/leits/MeetingBar/commit/819c4afcd10246ab511dc3fb80073a226a03cd88

2022-04-17 21:00 UTC, closed without merging

2022-04-18 17:04 UTC, jgoldhammer commented
Thanks for merging, @leits! It is really great to see this effort pays off!

2022-10-25 07:40 UTC, patrickrushton commented
Are these parameters also passed to the AppleScript which is run "when joining a meeting"?

If so, which event should I use in place of `on meetingStart` inside the joinEventScript.scpt?