Add Discord
leits/MeetingBar pull request #193
Opened 2021-02-19 17:43 UTC by NorthIsUp

2021-02-19 19:36 UTC, jgoldhammer commented
Thanks for the pull request. It is possible to compile without a (paid) developer account. The same for me. Nevertheless I will try to compile. Do you have a sample discord url for us to test with?

2021-02-25 18:15 UTC, jgoldhammer commented
Ping @NorthIsUp...

2021-03-02 07:45 UTC, 2Grey commented
@jgoldhammer, examples:

https://discord.com/channels/652753932904562709/778142129314463744
https://discord.com/channels/652753932904562709/778371290372374549

**Native**
discord://discord.com/@me
discord://discord.com/channels/652753932904562709/778142129314463744
discord://discord.com/channels/652753932904562709/778371290372374549

2021-03-03 09:16 UTC, 2Grey commented
@NorthIsUp, your code doesn't work for test links.

Patterns should be like:
_For Web_
`#"https://(canary\.)?discord\.com/channels/(\d+/\d+|@me)"#`
_For native_
`#"discord://(canary\.)?discord\.com/channels/(\d+/\d+|@me)"#`

2021-03-04 07:28 UTC, 2Grey commented on MeetingBar/Constants.swift
> +    let discord = try! NSRegularExpression(pattern: #"https://(canary.)?\.discord\.com/([0-9]+|@me)/[0-9]+"#)
```suggestion
    let discord = try! NSRegularExpression(pattern: #"https://(canary\.)?discord\.com/channels/(\d+/\d+|@me)"#)
```

2021-03-04 07:28 UTC, 2Grey commented on MeetingBar/Constants.swift
> +    let discord_native = try! NSRegularExpression(pattern: #"discord://(canary.)?\.discord\.com/([0-9]+|@me)/[0-9]+"#)
```suggestion
    let discord_native = try! NSRegularExpression(pattern: #"discord://(canary\.)?discord\.com/channels/(\d+/\d+|@me)"#)
```

2021-03-04 07:29 UTC, 2Grey commented on MeetingBar/Constants.swift
> +    let discord_native = try! NSRegularExpression(pattern: #"discord://(canary.)?\.discord\.com/([0-9]+|@me)/[0-9]+"#)
Fix native regexp

2021-03-04 07:29 UTC, 2Grey commented on MeetingBar/Constants.swift
> +    let discord = try! NSRegularExpression(pattern: #"https://(canary.)?\.discord\.com/([0-9]+|@me)/[0-9]+"#)
Fix web regexp

2021-03-04 07:30 UTC, 2Grey requested changes
Change regexp for Web and Native Discord links

2021-03-11 17:08 UTC, leits commented
@2Grey, I found this regular expression for discord:
`(https?:\/\/)?(www\.)?(discord\.(gg|io|me|li)|discordapp\.com\/invite)\/.+[a-z]`
Maybe we need to extend the regular expression to handle gg/io/me/li domains?
And maybe you know if /invite is different from /channel? 
Does it make sense to handle /invite?  Or event change regex to handle all endpoints under discord domain?

2021-03-12 17:30 UTC, 2Grey commented
@leits,
Maybe something more universal, like
`((https?|discord):\/\/)?(www\.)?(canary\.)?discord(app)?\.([a-zA-Z]{2,})(.+)?`

2021-03-15 21:23 UTC, leits submitted a review, later dismissed

2021-03-15 21:25 UTC, merged

2021-03-16 09:27 UTC, 2Grey commented
@leits, missing Discord image;

Add following code to `StatusBarItemControler.swift:346` class:

```swift
case .some(.discord):
            image = NSImage(named: "Discord-Logo-Color")!
            image?.size = NSSize(width: 16.0, height: 16.0)
```

2021-03-16 09:48 UTC, leits commented
Thanks, @2Grey. Already added in separate commit: https://github.com/leits/MeetingBar/commit/93bd428f7fc32da489b9a595fa8269c5df34e37c

2021-03-16 14:32 UTC, jgoldhammer commented
Hi @leits  - the discord app protocol pattern was not added, only the https link pattern. Any reason for this?

2021-03-16 14:36 UTC, leits commented
Hi, @jgoldhammer. @2Grey сombined them into one 👍