add localize for chinese-simple and chinese-traditional
leits/MeetingBar pull request #244
Opened 2021-04-17 17:38 UTC by hjw21century

### Status
READY

### Description
Add localization for chinese-simple and chinese-traditional language.

### Steps to Test or Reproduce
open the Preference panel and click the Generral page, then change the pickable to "简体中文"  or "繁体中文"

2021-04-17 17:49 UTC, hjw21century commented
![image](https://user-images.githubusercontent.com/7070409/115121983-219b7f80-9fe8-11eb-870e-91780ad6520b.png)
![image](https://user-images.githubusercontent.com/7070409/115122011-3f68e480-9fe8-11eb-8a76-9004dde8048e.png)

2021-04-18 21:46 UTC, leits commented on MeetingBar/Resources /Localization /zh-Hans.lproj/Localizable.strings
> +"preferences_calendars_add_account_modal" = "要添加外部日历，请执行以下步骤：\ n1。 打开默认日历应用程序\ n2。 单击菜单中的“添加帐户”\ n3。 选择并连接您的帐户";
```suggestion
"preferences_calendars_add_account_modal" = "要添加外部日历，请执行以下步骤：\n1。 打开默认日历应用程序\n2。 单击菜单中的“添加帐户”\n3。 选择并连接您的帐户";
```

2021-04-18 21:46 UTC, leits commented on MeetingBar/Resources /Localization /zh-Hans.lproj/Localizable.strings
> +"preferences_general_meeting_bar_description" = "会议栏是Andrii Leitsius创建的开源应用程序，Andrii Leitsius \ nthe app旨在使您的在线会议体验更顺畅，更容易";
```suggestion
"preferences_general_meeting_bar_description" = "会议栏是Andrii Leitsius创建的开源应用程序，Andrii Leitsius \nthe app旨在使您的在线会议体验更顺畅，更容易";
```

2021-04-18 21:55 UTC, leits requested changes
Hi, @hjw21century.
Thanks for the PR!
I review it and found a lot of typos.
Can you double-check localization?

2021-04-18 21:55 UTC, leits commented on MeetingBar/Resources /Localization /zh-Hans.lproj/Localizable.strings
> +"preferences_general_meeting_bar_description" = "会议栏是Andrii Leitsius创建的开源应用程序，Andrii Leitsius \ nthe app旨在使您的在线会议体验更顺畅，更容易";
```suggestion
"preferences_general_meeting_bar_description" = "会议栏是Andrii Leitsius创建的开源应用程序，Andrii Leitsius\nthe app旨在使您的在线会议体验更顺畅，更容易";
```

2021-04-18 21:55 UTC, leits commented on MeetingBar/Resources /Localization /zh-Hans.lproj/Localizable.strings
> +"preferences_calendars_add_account_modal" = "要添加外部日历，请执行以下步骤：\ n1。 打开默认日历应用程序\ n2。 单击菜单中的“添加帐户”\ n3。 选择并连接您的帐户";
```suggestion
"preferences_calendars_add_account_modal" = "要添加外部日历，请执行以下步骤：\n1。 打开默认日历应用程序\n2。 单击菜单中的“添加帐户”\n3。 选择并连接您的帐户";
```

2021-04-18 21:55 UTC, leits commented on MeetingBar/Resources /Localization /zh-Hans.lproj/Localizable.strings
> +"preferences_bookmarks_new_bookmark_already_exist" = "具有此链接/电话的书签已存在名称％@：\ n％@";
```suggestion
"preferences_bookmarks_new_bookmark_already_exist" = "具有此链接/电话的书签已存在名称％@：\n％@";
```

2021-04-18 21:55 UTC, leits commented on MeetingBar/Resources /Localization /zh-Hans.lproj/Localizable.strings
> +"preferences_services_supported_links_list" = "支持的服务链接：\ n％@";
```suggestion
"preferences_services_supported_links_list" = "支持的服务链接：\n％@";
```

2021-04-18 21:55 UTC, leits commented on MeetingBar/Resources /Localization /zh-Hant.lproj/Localizable.strings
> +"preferences_general_meeting_bar_description" = "會議欄是Andrii Leitsius創建的開源應用程序，Andrii Leitsius \ nthe app旨在使您的在線會議體驗更順暢，更容易";
```suggestion
"preferences_general_meeting_bar_description" = "會議欄是Andrii Leitsius創建的開源應用程序，Andrii Leitsius\nthe app旨在使您的在線會議體驗更順暢，更容易";
```

2021-04-18 21:55 UTC, leits commented on MeetingBar/Resources /Localization /zh-Hant.lproj/Localizable.strings
> +"preferences_services_supported_links_list" = "支持的服務鍊接：\ n％@";
```suggestion
"preferences_services_supported_links_list" = "支持的服務鍊接：\n％@";
```

2021-04-18 21:55 UTC, leits commented on MeetingBar/Resources /Localization /zh-Hant.lproj/Localizable.strings
> +"preferences_bookmarks_new_bookmark_already_exist" = "具有此鍊接/電話的書籤已存在名稱％@：\ n％@";
```suggestion
"preferences_bookmarks_new_bookmark_already_exist" = "具有此鍊接/電話的書籤已存在名稱％@：\n％@";
```

2021-04-18 21:55 UTC, leits commented on MeetingBar/Resources /Localization /zh-Hant.lproj/Localizable.strings
> +"preferences_calendars_add_account_modal" = "要添加外部日曆，請執行以下步驟：\ n1。 打開默認日曆應用程序\ n2。 單擊菜單中的“添加帳戶”\ n3。 選擇並連接您的帳戶";
```suggestion
"preferences_calendars_add_account_modal" = "要添加外部日曆，請執行以下步驟：\n1。 打開默認日曆應用程序\n2。 單擊菜單中的“添加帳戶”\n3。 選擇並連接您的帳戶";
```

2021-04-18 21:55 UTC, leits commented on MeetingBar/Resources /Localization /zh-Hans.lproj/Localizable.strings
> +"preferences_general_patron_six_months" = "6个月 -  5.99 USD";
```suggestion
"preferences_general_patron_six_months" = "6个月 -  5.99美元";
```

2021-04-18 21:55 UTC, leits commented on MeetingBar/Resources /Localization /zh-Hans.lproj/Localizable.strings
> +"preferences_general_external_gitHub" = "GitHub.";
```suggestion
"preferences_general_external_gitHub" = "GitHub";
```

2021-04-18 21:55 UTC, leits commented on MeetingBar/Resources /Localization /zh-Hans.lproj/Localizable.strings
> +"preferences_general_patron_thank_for_purchase" = "谢谢！ 您支持Meetabbar％DOMEN！ 🎉";
```suggestion
"preferences_general_patron_thank_for_purchase" = "谢谢！ 您支持MeetingBar ％d OMEN！ 🎉";
```

2021-04-18 21:55 UTC, leits commented on MeetingBar/Resources /Localization /zh-Hans.lproj/Localizable.strings
> +"preferences_general_patron_thank_for_purchase" = "谢谢！ 您支持Meetabbar％DOMEN！ 🎉";
OMEN?

2021-04-18 21:55 UTC, leits commented on MeetingBar/Resources /Localization /zh-Hans.lproj/Localizable.strings
> +"preferences_appearance_status_bar_icon_specific_icon_value" = "\ U00A0事件特定图标（I.N. MS团队）";
```suggestion
"preferences_appearance_status_bar_icon_specific_icon_value" = "\U00A0 事件特定图标（I.N. MS Teams）";
```

2021-07-02 14:56 UTC, leits commented
Closed because no response was received.

2021-07-02 14:56 UTC, closed without merging