Snooze notification event
leits/MeetingBar pull request #387
Opened 2021-12-05 11:09 UTC by niravbhimani53

### Status
**READY**

### Description
New feature to snooze the notification.
1. First Notification actions 
<img width="375" alt="Screen Shot 2021-12-05 at 10 01 07 pm" src="https://user-images.githubusercontent.com/12537912/144744033-65f51ce3-2424-4aaf-8b4e-265711bd75f4.png">
2. In case the user decides to snooze notification. `Snooze until start time` action will not be available
<img width="380" alt="Screen Shot 2021-12-05 at 10 04 25 pm" src="https://user-images.githubusercontent.com/12537912/144744045-af225d1f-8c72-4526-bfa9-b7dfd18aeac5.png">

## Checklist
- [ ] Localized
- [x] Added to changelog:
  - [x] [Changelog View](https://github.com/leits/MeetingBar/blob/master/MeetingBar/Views/Changelog/Changelog.swift)
  - [x] [CHANGELOG.md](https://github.com/leits/MeetingBar/blob/master/CHANGELOG.md)

### Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

2021-12-05 11:12 UTC, niravbhimani53 commented
@leits Can you please review the MR?

Cheers

2022-01-23 13:21 UTC, jgoldhammer commented
Sorry @niravbhimani53 - have not seen your merge request. Looks like a cool feature- really like it! 

I must dig deeper into it, especially how we structure the code around the snoozing. What do you think @leits ?

2022-01-25 11:47 UTC, leits commented
Thanks, @niravbhimani53!
I'll take a look!

2022-03-22 19:49 UTC, jgoldhammer requested changes
In general the PR looks fine. Can you please look at my comments? Thx a lot!

2022-03-22 19:49 UTC, jgoldhammer commented on MeetingBar/AppDelegate.swift
> +            }
This code blok repeats several times only with different parameters. Please refactor it so that the code is not repeated.

2022-03-22 19:49 UTC, jgoldhammer commented on MeetingBar/AppDelegate.swift
> +        case "SNOOZE_15_MIN", UNNotificationDefaultActionIdentifier:
Currently the different durations are not connected in the code. We have the strings "SNOOZE_30_MIN" and the .thirtyMinuteLater. Can you use please use enums for it? (https://blog.logrocket.com/swift-enums-an-overview-with-examples/)

2022-03-22 19:49 UTC, jgoldhammer commented on MeetingBar/Constants.swift
> +}
Question: Can we support 10 minutes as well?

2022-03-23 11:01 UTC, niravbhimani53 commented on MeetingBar/Constants.swift
> +}
Sure. I will push changes over the weekend. Thanks for feedback.

2022-03-26 04:36 UTC, niravbhimani53 commented on MeetingBar/Constants.swift
> +}
Yes, we can support 10 mins. I will add that

2022-04-03 10:39 UTC, niravbhimani53 commented on MeetingBar/Constants.swift
> +}
I have added support for 10 mins.

2022-04-03 10:40 UTC, niravbhimani53 commented on MeetingBar/AppDelegate.swift
> +        case "SNOOZE_15_MIN", UNNotificationDefaultActionIdentifier:
I have refactored the code.

2022-04-03 10:40 UTC, niravbhimani53 commented on MeetingBar/AppDelegate.swift
> +            }
Done.

2022-04-03 10:42 UTC, niravbhimani53 commented
> In general the PR looks fine. Can you please look at my comments? Thx a lot!

Apologies for the delay.

@jgoldhammer MR is ready for review. Waiting for your feedback.

Cheers :)

2022-04-04 17:05 UTC, jgoldhammer commented on MeetingBar/Constants.swift
> +}
Thanks. LGTM!

2022-04-04 17:05 UTC, jgoldhammer commented
> > In general the PR looks fine. Can you please look at my comments? Thx a lot!
> 
> Apologies for the delay.
> 
> @jgoldhammer MR is ready for review. Waiting for your feedback.
> 
> Cheers :)

No problem at all. Thanks for your work!! I will review it more in detail now...

2022-04-04 17:45 UTC, jgoldhammer commented
Sorry @niravbhimani53 - I have updated your branch while there were some mini conflicts, but now linting failed. I have opened a PR so that you can merge the changes for the lint errors on your side, so that the PR gets updated.
Thanks!

2022-04-10 15:06 UTC, jgoldhammer approved these changes

2022-04-10 15:06 UTC, jgoldhammer commented
Tested it locally- works fine! Good work @niravbhimani53 !I will merge now...

2022-04-10 15:07 UTC, merged